### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by jbeck28** [PickNikRobotics/descartes_capability#3]
`error: no matching function for call to ‘descartes_moveit::MoveitStateAdapter::initialize(planning_scene_monitor::PlanningSceneMonitorPtr&, const string&, const string&, const string&)’
       moveit_state_adapter->initialize(context_->planning_scene_monitor_, group_name, world_frame, tcp_frame);
                                                                                                             ^
In file included from /home/rnd/catkin_ws/src/descartes/descartes_moveit/include/descartes_moveit/ikfast_moveit_state_adapter.h:22:0,
                 from /home/rnd/catkin_ws/src/descartes_capability/include/descartes_capability/descartes_path_service_capability.h:49,
                 from /home/rnd/catkin_ws/src/descartes_capability/src/descartes_path_service_capability.cpp:41:
/home/rnd/catkin_ws/src/descartes/descartes_moveit/include/descartes_moveit/moveit_state_adapter.h:43:16: note: candidate: virtual bool descartes_moveit::MoveitStateAdapter::initialize(const string&, const string&, const string&, const string&)
   virtual bool initialize(const std::string &robot_description, const std::string &group_name,
                ^~~~~~~~~~
/home/rnd/catkin_ws/src/descartes/descartes_moveit/include/descartes_moveit/moveit_state_adapter.h:43:16: note:   no known conversion for argument 1 from ‘planning_scene_monitor::PlanningSceneMonitorPtr {aka std::shared_ptr<planning_scene_monitor::PlanningSceneMonitor>}’ to ‘const string& {aka const std::__cxx11::basic_string<char>&}’
/home/rnd/catkin_ws/src/descartes/descartes_moveit/include/descartes_moveit/moveit_state_adapter.h:46:16: note: candidate: virtual bool descartes_moveit::MoveitStateAdapter::initialize(moveit::core::RobotModelConstPtr, const string&, const string&, const string&)
   virtual bool initialize(robot_model::RobotModelConstPtr robot_model, const std::string &group_name,
                ^~~~~~~~~~
/home/rnd/catkin_ws/src/descartes/descartes_moveit/include/descartes_moveit/moveit_state_adapter.h:46:16: note:   no known conversion for argument 1 from ‘planning_scene_monitor::PlanningSceneMonitorPtr {aka std::shared_ptr<planning_scene_monitor::PlanningSceneMonitor>}’ to ‘moveit::core::RobotModelConstPtr {aka std::shared_ptr<const moveit::core::RobotModel>}’
`

This seems to be caused by the fact that the descartes package does not have an initialize member which takes in a planning_scene_monitor.

Edit: Running Melodic, latest version of descartes

**Comment by mlautman** [comment]
I am pretty sure you  aren't using the correct branch of the descartes fork. You should be using the one in the rosinstall
