### ISSUE TITLE
Discontinuous Paths

### ISSUE THREAD

**Issue by jbeck28** [PickNikRobotics/descartes_capability#4]
I've been trying to plan circular paths using this plugin and opw kinematics for a Fanuc LRmate200id. I'm using the following plugin for opw

https://github.com/JeroenDM/moveit_opw_kinematics_plugin

this seems to work fine when using the the built-in moveit computecartesianpath functionality. However, when I switch to descarte, I find that path planning fails more often, and even when it succeeds in planning a path, the trajectory is riddled with discontinuous joint flips. This happened while using TRAC-IK as well. 

This is likely due to some problem I've encountered while setting this software up, so any pointers on where to look and what to check would be much appreciated.

**Comment by gavanderhoorn** [comment]
For reference, original ROS Answers question: [Descartes finding discontinuous path](https://answers.ros.org/question/323959).

**Comment by jbeck28** [comment]
Just going to update this slightly... I have since gotten OPW to work with descartes (not using this repository), by means  of the [descartes_opw_model](https://github.com/JeroenDM/descartes_opw_model). So I believe this was an issue with descartes not being given a full set of joint solutions, or not being able to properly compute the weights.

**Comment by davetcoleman** [comment]
@mlautman is the go-to on this capability

**Comment by mlautman** [comment]
Sounds like you found a resolution.
